#!/bin/bash

ping -c 1 google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 google.com.tr | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 gmail.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 mail.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 plus.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 gmail.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 imap.gmail.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 smtp.gmail.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 pop.gmail.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 images.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 youtube.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 maps.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 docs.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 drive.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 translate.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 translate.google.com.tr | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 code.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 dl.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 clients1.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 myaccount.google.com | gawk -F'[()]' '/PING/{print $1 $2}'
ping -c 1 encrypted.google.com | gawk -F'[()]' '/PING/{print $1 $2}'